### ISSUE TITLE
Consider multitask support & standardized configuration

### ISSUE THREAD

**Issue by jsoverson** [geddski/grunt-symlink#1]
It would be nice if this was a multitask so that different configurations could be handled more easily.

Using grunt 0.4.0 you could also standardize the config more via:

``` js
symlink : {
  taskName : {
    files : {
      'destination.link' : 'source.file',
      'destination2.link' : 'source2.file'
    },
  }
  taskName2 : {
    src : 'source.file',
    dest : 'dest.link',
    options : {
      type : 'dir
    }
  }
}
```

**Comment by geddski** [comment]
Good ideas. I like multitasks better as well. [0.2.0](https://github.com/geddesign/grunt-symlink/commit/54c0e09b4bceb86419455ed9eb74cdf0587b3443) turns this into a multitask like you suggested, with a more consistent config. 

I used `relativeSrc` rather than `src`, because people would expect `src` to be relative to the project root like it is for every other grunt task. `relativeSrc` is relative to the `dest` directory, so this may avoid some confusion. 

Thanks for contributing, let me know how you like the updates.
